### ISSUE TITLE
Errors in using pretrained models

### ISSUE THREAD

**Issue by JinyinZha** [lujiarui/Str2Str#1]
Hi! I am trying to predict protein ensembles by using the pretrained model offered on Google Drive (named pretrain.pth). However, something seems to be wrong when loading the state dict.

my command: `python eval.py task_name=inference target_dir=null ckpt_path=/home/jyzha/software/Str2Str/data/pretrain.pth`

the output and error after printing config: 

> [2024-03-07 13:48:24,178][__main__][INFO] - [rank: 0] Instantiating datamodule <src.data.protein_datamodule.ProteinDataModule>
[2024-03-07 13:48:24,187][__main__][INFO] - [rank: 0] Instantiating model <src.models.diffusion_module.DiffusionLitModule>
/home/jyzha/software/anaconda3/envs/str2str/lib/python3.9/site-packages/torch/nn/modules/transformer.py:286: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
/home/jyzha/software/anaconda3/envs/str2str/lib/python3.9/site-packages/lightning/pytorch/utilities/parsing.py:199: Attribute 'net' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['net'])`.
[2024-03-07 13:48:28,277][__main__][INFO] - [rank: 0] Instantiating loggers...
[2024-03-07 13:48:28,278][src.utils.instantiators][WARNING] - [rank: 0] No logger configs found! Skipping...
[2024-03-07 13:48:28,278][__main__][INFO] - [rank: 0] Instantiating trainer <lightning.pytorch.trainer.Trainer>
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2024-03-07 13:48:28,512][src.utils.utils][ERROR] - [rank: 0]
Traceback (most recent call last):
  File "/home/jyzha/software/Str2Str/src/utils/utils.py", line 68, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/jyzha/software/Str2Str/src/eval.py", line 144, in evaluate
    model, ckpt_path = checkpoint_utils.load_model_checkpoint(model, cfg.ckpt_path)
  File "/home/jyzha/software/Str2Str/src/utils/checkpoint_utils.py", line 19, in load_model_checkpoint
    model.net.load_state_dict(net_params)
  File "/home/jyzha/software/anaconda3/envs/str2str/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DenoisingNet:
        Unexpected key(s) in state_dict: "translator.trunk.ipa_0.linear_rbf.weight", "translator.trunk.ipa_0.linear_rbf.bias", "translator.trunk.ipa_1.linear_rbf.weight", "translator.trunk.ipa_1.linear_rbf.bias", "translator.trunk.ipa_2.linear_rbf.weight", "translator.trunk.ipa_2.linear_rbf.bias", "translator.trunk.ipa_3.linear_rbf.weight", "translator.trunk.ipa_3.linear_rbf.bias".
[2024-03-07 13:48:28,516][src.utils.utils][INFO] - [rank: 0] Output dir: /home/jyzha/software/Str2Str/logs/inference/runs/2024-03-07_13-48-23
Error executing job with overrides: ['task_name=inference', 'target_dir=null', 'ckpt_path=/home/jyzha/software/Str2Str/data/pretrain.pth']
Traceback (most recent call last):
  File "/home/jyzha/software/Str2Str/src/eval.py", line 173, in main
    evaluate(cfg)
  File "/home/jyzha/software/Str2Str/src/utils/utils.py", line 78, in wrap
    raise ex
  File "/home/jyzha/software/Str2Str/src/utils/utils.py", line 68, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/jyzha/software/Str2Str/src/eval.py", line 144, in evaluate
    model, ckpt_path = checkpoint_utils.load_model_checkpoint(model, cfg.ckpt_path)
  File "/home/jyzha/software/Str2Str/src/utils/checkpoint_utils.py", line 19, in load_model_checkpoint
    model.net.load_state_dict(net_params)
  File "/home/jyzha/software/anaconda3/envs/str2str/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DenoisingNet:
        Unexpected key(s) in state_dict: "translator.trunk.ipa_0.linear_rbf.weight", "translator.trunk.ipa_0.linear_rbf.bias", "translator.trunk.ipa_1.linear_rbf.weight", "translator.trunk.ipa_1.linear_rbf.bias", "translator.trunk.ipa_2.linear_rbf.weight", "translator.trunk.ipa_2.linear_rbf.bias", "translator.trunk.ipa_3.linear_rbf.weight", "translator.trunk.ipa_3.linear_rbf.bias".
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

I am looking for the solution to fix it and very thanks.

**Comment by lujiarui** [comment]
Hi @JinyinZha, thanks for pointing out this bug. Now it is fixed with the newly uploaded gdrive link to the model weight. Please download the `.pth` file again.
