### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by llllly26** [lujiarui/Str2Str#6]
Hi, thanks for your work!
when I ran 
```
# Preprocess.
python scripts/pdb/preprocess.py --mmcif_dir $DOWNLOAD_DIR/pdb_mmcif/mmcif_files --output_dir $PROCESSED_DIR
```
I met this problem, how to solve it?
`The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
>>> Globbing mmCIF paths w/ [file-size] filter
>>> Select 220757 files out of 220760 by file size (debug=False)
Files will be written to ./processed_dir
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/miniconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/miniconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/Str2Str/scripts/pdb/preprocess.py", line 447, in process_fn
    metadata = process_mmcif_file(
  File "/home/Str2Str/scripts/pdb/preprocess.py", line 403, in process_mmcif_file
    min_modeled_idx = np.min(modeled_idx)
  File "<__array_function__ internals>", line 200, in amin
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2946, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/Str2Str/scripts/pdb/preprocess.py", line 557, in <module>
    main(args)
  File "/home/Str2Str/scripts/pdb/preprocess.py", line 512, in main
    _all_metadata = pool.map(_process_fn, all_mmcif_paths)
  File "/home/miniconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/miniconda3/envs/myenv/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: zero-size array to reduction operation minimum which has no identity
`

**Comment by llllly26** [comment]
Is anybody? by the way, how to add `train_data` and `test_data` dir? Could you give an example?

**Comment by lujiarui** [comment]
Did you assign value to the variable $DOWNLOAD_DIR and $PROCESSED_DIR? Then you could try using single process and find out where the error is.

**Comment by lujiarui** [comment]
> Is anybody? by the way, how to add `train_data` and `test_data` dir? Could you give an example?

TRAIN_DATA (TEST_DATA as well) will be passed as an argument in https://github.com/lujiarui/Str2Str/blob/main/src/data/components/dataset.py#L199. It could be directory of pdb files or glob pattern or csv table file (if you process using the script).

**Comment by llllly26** [comment]
> Did you assign value to the variable DOWNLOADDIRandDOWNLOADDIRandDOWNLOAD_DIR and PROCESSED_DIR? Then you could try using single process and find out where the error is.

thanks @lujiarui ! This error is caused by multiprocessing. 

I saw that when I run `python scripts/pdb/preprocess.py --mmcif_dir $DOWNLOAD_DIR/pdb_mmcif/mmcif_files --output_dir $PROCESSE`, and generate a `metadata.csv`. So I changed `TRAIN_DATA` and `TEST_DATA` in `.env` to dir of `metadata.csv`. Is that right?  In this way, when I run train script, occurring the error: 

`KeyError: 'processed_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/Str2Str/src/data/components/dataset.py", line 298, in __init__
    super(PretrainPDBDataset, self).__init__(path_to_dataset=path_to_dataset,
  File "/home/Str2Str/src/data/components/dataset.py", line 219, in __init__
    self._data = self._df['processed_path'].tolist()
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'processed_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/Str2Str/src/utils/utils.py", line 68, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/Str2Str/src/train.py", line 59, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.data)
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.data.components.dataset.PretrainPDBDataset':
KeyError('processed_path')
full_key: data.dataset
[2024-06-12 11:24:47,174][src.utils.utils][INFO] - [rank: 0] Output dir: /home/Str2Str/logs/train/runs/2024-06-12_11-24-46
Error executing job with overrides: ['trainer=gpu']
Traceback (most recent call last):
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'processed_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/Str2Str/src/data/components/dataset.py", line 298, in __init__
    super(PretrainPDBDataset, self).__init__(path_to_dataset=path_to_dataset, 
  File "/home/Str2Str/src/data/components/dataset.py", line 219, in __init__
    self._data = self._df['processed_path'].tolist()
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'processed_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/Str2Str/src/train.py", line 135, in <module>
    main()
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/Str2Str/src/train.py", line 123, in main
    metric_dict, _ = train(cfg)
  File "/home/Str2Str/src/utils/utils.py", line 78, in wrap
    raise ex
  File "/home/Str2Str/src/utils/utils.py", line 68, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/Str2Str/src/train.py", line 59, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.data)
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/home/miniconda3/envs/myenv/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.data.components.dataset.PretrainPDBDataset':
KeyError('processed_path')
full_key: data.dataset`

Maybe this bug is also caused by the path, but I am sorry that I am unfamiliar with your project, so how to solve it? thanks!

**Comment by lujiarui** [comment]
As mentioned previously, the `TRAIN_DATA` and `TEST_DATA` should be either path to `metadata.csv`, or a directory of pdb files,  or a glob pattern of pdb/pkl files
